language: go

go:
- "1.14"


os:
- linux
- osx

git:
  depth: 1

before_install:
- go get github.com/danieldn/tc

script:
- go test -v ./... | tc
- go build

gobuild_args: -ldflags "-X 'main.version=v0.1.0'"
